site_name: napari-colocalisation
site_description: Intensity colocalisation analysis for napari.
site_url: https://DBI-INFRA.github.io/napari-colocalisation/
repo_url: https://github.com/DBI-INFRA/napari-colocalisation
repo_name: DBI-INFRA/napari-colocalisation
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Usage: usage.md
  - Metrics: metrics.md
  - Python API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_root_heading: false
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            members_order: source
            merge_init_into_class: true
            filters:
              - "!^_"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.']
      check_paths: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
